### ISSUE TITLE
Warnings on Word List

### ISSUE THREAD

**Issue by aymux** [alphacep/vosk-api#159]
_( Python 3 on Rpi 3b+ with French model)_
Hi !
So, using the KaldiRecognizer with word list, if get LOGs and WARNINGs for words not included in the list.
For ex. word list with spoker numbers ('un deux trois quatre cinq...")
If i say 'Hello there' or anything I get this type of output :

> LOG (VoskAPI:RebuildRepository():determinize-lattice-pruned.cc:287) Rebuilding repository.
WARNING (VoskAPI:CheckMemoryUsage():determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (32486304,743860,16772896), after rebuilding, repo size was 24276960, effective beam was 3.57752 vs. requested beam 6

plus the recog. takes longer time...

Is there a way to configure VOSK to pass on non listed words ? Or something else I should try ?

Thanks ^^

**Comment by nshmyrev** [comment]
This should be fixed in https://github.com/alphacep/vosk-api/commit/55ba22989361db509a781a91612df5a31d69843b

Thank you for the report

**Comment by aymux** [comment]
Hi again. So after LOOOOong time i compiled Kaldi and vosk-api on Rpi to test again.
I still have the same warnings after your update.
ps I'm using french model. I tested with english one and it partially worked. I got the UNK token but still warnings.

- In fact - I'm trying to detect only specified words and reject others. Is this possible ? 
  If i provide word list, other words are still recognized but they are 'seen' as words in list... 
  e.g. if word list is _"one two three .... [unk]"_  and wav file is _"I want some cake"_ 
   (in french _"un deux trois .... [unk]"_ and wav _"Je veux du gateau"_)
   results gives me (in french) "**deux deux quatre [unk]**" 
   which is phonetically close but not what i want...

**Comment by mieszkokl** [comment]
Hi, I have the same issue with the English model.
I have limited list of words (with "[unk]" attached) and when I say words that are not in the list, after some time I get info about rebuilding repository which blocks further recognition.

**Comment by nshmyrev** [comment]
Ok, great, let me take a look again

**Comment by nshmyrev** [comment]
@mieszkokl it would help if you provide the word list and the audio sample to reproduce your problem between.

**Comment by mieszkokl** [comment]
Words list:
`"test word bug [unk]"`

Audio sample: https://drive.google.com/file/d/1TV2m-wfy6frnybPh0X7Ta91sc81yLMV1/view?usp=sharing

It detects words correctly, but when it starts to rebuild repository, it's no more real time.

**Comment by mieszkokl** [comment]
Update:
I was able to get rid of rebuilding repository by reducing lattice-beam in model.cc. Is it safe? Can something go wrong with this?

**Comment by nshmyrev** [comment]
Yes, it is ok, thank you. I wanted to implement things a bit differently with full LM constructed from phrases but it will probably take couple more weeks.

**Comment by nshmyrev** [comment]
This should be better with new bigram grammars pushed in commit 57cc474c9fd7fc7ce36088a5756aa2b43c7dd0b2

Please test and I'll close

**Comment by aymux** [comment]
Hi again !
So I tested again and this is OK for me. No more warnings.
Raspberry builds are a pain, so i tested the dockcross solution. Works great ! A bit confusing for a newbie like me at start...
But i finally managed to build vosk python wheel on a Ubuntu VM.
Thanks for the great work ^^

**Comment by nshmyrev** [comment]
Great, let me know if you have further questions then.
