### ISSUE TITLE
 --add-pitch=true 

### ISSUE THREAD

**Issue by dpny518** [alphacep/vosk-api#442]
I know your chinese model doesn't use pitch, but many models do, could you kindly accept this parameter in the docker and api

Thank you

ERROR (VoskAPI:ReadConfigFile():parse-options.cc:493) Invalid option --add-pitch=true in config file /opt/vosk-model-cn/model/conf/model.conf
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError

**Comment by nshmyrev** [comment]
I pushed a fix, if you add pitch.conf, it will enable pitch.

**Comment by v-yunbin** [comment]
@nshmyrev I update my codes，but still not load pitch feature
`['test_text.py']
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:192) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:195) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.019125 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:237) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:256) Loading words from model/words.txt
ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 40 but network expects 43
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
Aborted (core dumped)
`

**Comment by zyb8543d** [comment]
@nshmyrev I update my codes，it still not load pitch feature
```
pip list | grep "vosk"
vosk                      0.3.21
```              
`LOG (VoskAPI:ReadDataFiles():model.cc:194) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:197) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0204771 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:246) Loading HCLG from model/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:265) Loading words from model/words.txt
ERROR (VoskAPI:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:46) Input feature dimension mismatch: got 40 but network expects 43
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
`

**Comment by zyb8543d** [comment]
@yondu22 have you test successfully with  pitch ?

**Comment by nshmyrev** [comment]
@v-yunbin we didn't release the updated code yet, you have to rebuild from source, did you rebuild?

**Comment by zyb8543d** [comment]
I rebuild it, but met some errors:
```
**_Step1_**:cd src/ &&  $KALDI_ROOT=/opt/kaldi/ make  
g++ --shared -s -o libvosk.so kaldi_recognizer.o language_model.o model.o spk_model.o vosk_api.o /opt/kaldi//src/online2/kaldi-online2.a /opt/kaldi//src/decoder/kaldi-decoder.a /opt/kaldi//src/ivector/kaldi-ivector.a /opt/kaldi//src/gmm/kaldi-gmm.a /opt/kaldi//src/nnet3/kaldi-nnet3.a /opt/kaldi//src/tree/kaldi-tree.a /opt/kaldi//src/feat/kaldi-feat.a /opt/kaldi//src/lat/kaldi-lat.a /opt/kaldi//src/lm/kaldi-lm.a /opt/kaldi//src/hmm/kaldi-hmm.a /opt/kaldi//src/transform/kaldi-transform.a /opt/kaldi//src/cudamatrix/kaldi-cudamatrix.a /opt/kaldi//src/matrix/kaldi-matrix.a /opt/kaldi//src/fstext/kaldi-fstext.a /opt/kaldi//src/util/kaldi-util.a /opt/kaldi//src/base/kaldi-base.a /opt/kaldi//tools/OpenBLAS/install/lib/libopenblas.a /opt/kaldi//tools/OpenBLAS/install/lib/liblapack.a /opt/kaldi//tools/OpenBLAS/install/lib/libblas.a /opt/kaldi//tools/OpenBLAS/install/lib/libf2c.a /opt/kaldi//tools/openfst/lib/libfst.a /opt/kaldi//tools/openfst/lib/libfstngram.a -lm -latomic
**_Step2_**  cd ../python/ && python setup.py install  
Adding library /home/ybZhang/vosk-api/src/libvosk.so
running install
running bdist_egg
running egg_info
writing vosk.egg-info/PKG-INFO
writing dependency_links to vosk.egg-info/dependency_links.txt
writing requirements to vosk.egg-info/requires.txt
writing top-level names to vosk.egg-info/top_level.txt
reading manifest file 'vosk.egg-info/SOURCES.txt'
writing manifest file 'vosk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
creating build/lib
creating build/lib/vosk
copying vosk/__init__.py -> build/lib/vosk
copying vosk/vosk.py -> build/lib/vosk
copying vosk/kaldi_recognizer.cc -> build/lib/vosk
copying vosk/language_model.cc -> build/lib/vosk
copying vosk/model.cc -> build/lib/vosk
copying vosk/spk_model.cc -> build/lib/vosk
copying vosk/vosk.i -> build/lib/vosk
copying vosk/vosk_api.cc -> build/lib/vosk
copying vosk/libvosk.so -> build/lib/vosk
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
generating cffi module 'build/lib/vosk/vosk_cffi.py'
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/__init__.py -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/vosk.py -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/kaldi_recognizer.cc -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/language_model.cc -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/model.cc -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/spk_model.cc -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/vosk.i -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/vosk_api.cc -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/libvosk.so -> build/bdist.linux-x86_64/egg/vosk
copying build/lib/vosk/vosk_cffi.py -> build/bdist.linux-x86_64/egg/vosk
byte-compiling build/bdist.linux-x86_64/egg/vosk/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/vosk/vosk.py to vosk.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/vosk/vosk_cffi.py to vosk_cffi.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying vosk.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating dist
creating 'dist/vosk-0.3.21-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing vosk-0.3.21-py3.8.egg
creating /home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg
Extracting vosk-0.3.21-py3.8.egg to /home/ybZhang/miniconda3/lib/python3.8/site-packages
Adding vosk 0.3.21 to easy-install.pth file

Installed /home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg
Processing dependencies for vosk==0.3.21
Searching for cffi==1.14.0
Best match: cffi 1.14.0
Adding cffi 1.14.0 to easy-install.pth file

Using /home/ybZhang/miniconda3/lib/python3.8/site-packages
Searching for pycparser==2.20
Best match: pycparser 2.20
Adding pycparser 2.20 to easy-install.pth file

Using /home/ybZhang/miniconda3/lib/python3.8/site-packages
Finished processing dependencies for vosk==0.3.21
**_Step3_**：cd example/ && python test_text.py 2ae1fec4-0fd6-4d31-87e6-edefc021ee22.wav   
Traceback (most recent call last):
  File "test_text.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer
  File "/home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg/vosk/__init__.py", line 21, in <module>
    _c = open_dll()
  File "/home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg/vosk/__init__.py", line 15, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
OSError: cannot load library '/home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg/vosk/libvosk.so': /home/ybZhang/miniconda3/lib/python3.8/site-packages/vosk-0.3.21-py3.8.egg/vosk/libvosk.so: undefined symbol: _Z26FLAGS_fst_weight_separatorB5cxx11
```

**Comment by dpny518** [comment]
@v-yunbin why don't you just build the docker instead, its safer so you don't mess up your native computer
https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-vosk-server

then change the model and Docker  to your local one
https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-cn

**Comment by zyb8543d** [comment]
@yondu22 good idea! I notice that, I'll think about it later

**Comment by nshmyrev** [comment]
@yondu22 @v-yunbin sorry, docker is not updated, you have to rebuild pip

as for library error, not sure what is wrong here, you'd better build clean kaldi from scratch.

**Comment by zyb8543d** [comment]
@nnkalita In fact, I have builded a clean kaldi
I find when i run the cammand “ python setup.py install”， it echo some error info ：
```
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
copying vosk/libvosk.so -> build/lib/vosk
file vosk/vosk_cffi.py (for module vosk.vosk_cffi) not found
generating cffi module 'build/lib/vosk/vosk_cffi.py
```
I seems that it can not find the script "vosk_cffi.py" but i find it in folder "build/lib/vosk"

**Comment by nshmyrev** [comment]
> I seems that it can not find the script "vosk_cffi.py" but i find it in folder "build/lib/vosk"

its ok, not critical

**Comment by zyb8543d** [comment]
@nshmyrev I have rebuild openfst 、 openblas and kaldi successfully，it still not work. maybe it is hard for me.
```
ld libvosk.so 
ld: warning: cannot find entry symbol _start; not setting start address
libvosk.so: undefined reference to `fst::FstReadOptions::FstReadOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fst::FstHeader const*, fst::SymbolTable const*, fst::SymbolTable const*)'
libvosk.so: undefined reference to `fst::FstHeader::Write(std::ostream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.so: undefined reference to `fst::MappedFile::Map(std::istream*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
libvosk.so: undefined reference to `fst::ConvertToLegalCSymbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)'
libvosk.so: undefined reference to `fst::FstHeader::Read(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
libvosk.so: undefined reference to `dlopen'
libvosk.so: undefined reference to `fst::internal::DenseSymbolMap::Find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
libvosk.so: undefined reference to `FLAGS_fst_weight_separator[abi:cxx11]'
libvosk.so: undefined reference to `FLAGS_save_relabel_opairs[abi:cxx11]'
libvosk.so: undefined reference to `_gfortran_concat_string'
libvosk.so: undefined reference to `dlerror'
libvosk.so: undefined reference to `fst::internal::SymbolTableImpl::AddSymbol(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, long)'
libvosk.so: undefined reference to `fst::internal::SymbolTableImpl::ReadText(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, fst::SymbolTableTextOptions const&)'
libvosk.so: undefined reference to `FLAGS_save_relabel_ipairs[abi:cxx11]'
```

it seems that the problem from openfst, but I have build it successfull.

**Comment by nshmyrev** [comment]
> @nshmyrev I have rebuild openfst 、 openblas and kaldi successfully，it still not work. maybe it is hard for me.

Are you building with docker or what? Do you follow docker build process?
