### ISSUE TITLE
Using prebuilt library for node on macos

### ISSUE THREAD

**Issue by jide** [alphacep/vosk-api#458]
The documentation says : 
"To use it you need to compile libvosk library, see Python module build instructions for details. You can find prebuilt library inside python wheel."

Does this mean that there is a prebuilt library somewhere suitable for use with node ? On macos ?
The vosk npm package includes a lib folder with .so files, are these prebuilt libraries ?

**Comment by nshmyrev** [comment]
> Does this mean that there is a prebuilt library somewhere suitable for use with node ? On macos ?

Yes, the library is the same between bindings - python, node, java

> The vosk npm package includes a lib folder with .so files, are these prebuilt libraries ?

Yes

**Comment by nshmyrev** [comment]
As for OSX, I don't think the library is available, we shall compile it soon.

**Comment by jide** [comment]
Ah ok, that is probably the missing .so.dylib file then I guess. I saw some earlier releases include a macos build, is that correct ? : 
https://github.com/alphacep/vosk-api/releases/tag/0.3.15

In this case, how one could use this build with the npm package ? I do not see the .so.dylib in this wheel, I am missing something ?

**Comment by jide** [comment]
For context, when running a node script using vosk, it throws : 

```
/Users/jide/Projects/s10d/s10d-platform-lambdas/transcribe/node_modules/vosk/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: dlopen(/Users/jide/Projects/s10d/s10d-platform-lambdas/transcribe/node_modules/vosk/lib/linux-x86_64/libvosk.so.dylib, 2): image not found
```

**Comment by nshmyrev** [comment]
You need to change this part too and introduce a check for Darwin:

https://github.com/alphacep/vosk-api/blob/a5a3697b7c79114384e47df8fd89010ad4277c41/nodejs/index.js#L15

I would try to recompile library with kaldi from latest version but you need Xcode 9.3, older version doesn't work. So it will take some significant effort for me personally to upgrade.

**Comment by jide** [comment]
Thanks, actually, that was the path I was following. But compiling the lib with kaldi seems scary I must say. I'll probably stick with the linux build for now, and watch for a macos build.

**Comment by nshmyrev** [comment]
@jide actually I've just pushed 0.3.22 to npm, please try, it should include osx binary and should work.

**Comment by jide** [comment]
Wow that was fast, thanks for taking the time to do this.

I tried, but it still throws, complaining about the missing dylib again : 
```
/Users/jide/Projects/s10d/s10d-platform-lambdas/transcribe/node_modules/vosk/node_modules/ffi-napi/lib/dynamic_library.js:75
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: dlopen(/Users/jide/Projects/s10d/s10d-platform-lambdas/transcribe/node_modules/vosk/lib/linux-x86_64/libvosk.so.dylib, 2): image not found
```

**Comment by jide** [comment]
Hmmm I think the problem is with the os check, since it is looking for `linux-x86_64/libvosk.so.dylib`, it should be `osx-x86_64/libvosk.so.dylib`

**Comment by jide** [comment]
I think there's a typo here https://github.com/alphacep/vosk-api/commit/42cd30f7c8281cb03ab0f8effd5ec1976af764bf#diff-5c59fd8243402577a3accd0193ed1e48790a48c57ae4721457ea1d3a6cc47320R18

Should be "darwin" ?

**Comment by nshmyrev** [comment]
yes

**Comment by nshmyrev** [comment]
Try 0.3.23

**Comment by jide** [comment]
It works ! Thanks a lot.

**Comment by nshmyrev** [comment]
Ok, great!
