### ISSUE TITLE
"Illegal Instruction" on test with Raspbian

### ISSUE THREAD

**Issue by jbaber** [alphacep/vosk-api#48]
On a Raspberry Pi Zero W with Raspbian 10 buster.

    sudo apt-get install libgfortran-6-dev
    pip3 install --user vosk
    cd vosk-api/python/example
    wget https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-en-us-0.3.tar.gz
    tar xf alphacep-model-android-en-us-0.3.tar.gz
    mv alphacep-model-android-en-us-0.3 model-en
    python3 ./test_simple.py test.wav
    Illegal instruction

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/46

We will upload new pip soon. For now please install with

pip install https://github.com/alphacep/vosk-api/releases/download/0.3.3/vosk-0.3.3-cp37-cp37m-linux_armv6l.whl

**Comment by nshmyrev** [comment]
It should be fixed now

**Comment by jbaber** [comment]
Thanks!

**Comment by girishsukukumar** [comment]
I still get this error 
When I tried to install using 
pip install https://github.com/alphacep/vosk-api/releases/download/0.3.3/vosk-0.3.3-cp37-cp37m-linux_armv6l.whl
ERROR: vosk-0.3.3-cp37-cp37m-linux_armv6l.whl is not a supported wheel on this platform.


I am using raspberry Pi-3 
 uname -a
Linux tts 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
I get an error

**Comment by girishsukukumar** [comment]
I tried
sudo pip install https://github.com/alphacep/vosk-api/releases/download/0.3.10/vosk-0.3.10-cp37-cp37m-linux_armv7l.whl
ERROR: vosk-0.3.10-cp37-cp37m-linux_armv7l.whl is not a supported wheel on this platform.
