### ISSUE TITLE
Compiling python module on MacOS 10.15

### ISSUE THREAD

**Issue by jose-alvessh** [alphacep/vosk-api#88]
Hi guys,

I'm trying to use vosk-api python module in MacOSX but i'm not being able to create to compile it from source.
I've followed the steps from the readme file of compiling from source and everything run without any problem until the step:
`python3 setup.py install --user --single-version-externally-managed --root=/`
First time I got this error: **library not found for -lgfortran.**

Then, following instructions from @nshmyrev, I have tried to replace the path to the openblas.a and the flag -lgfortran for the -frameword Accelerate. My CMakeLists.txt now look like this:

````
cmake_minimum_required(VERSION 3.12.0)
project(vosk)

set(TOP_SRCDIR "${CMAKE_SOURCE_DIR}/..")
if("x$ENV{WHEEL_FLAGS}" STREQUAL "x")
find_package (Python3 COMPONENTS Interpreter Development)
else()
set(Python3_INCLUDE_DIRS "")
set(TOP_SRCDIR "/io")
endif()

set(KALDI_ROOT "$ENV{KALDI_ROOT}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DFST_NO_DYNAMIC_LINKING")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} $ENV{WHEEL_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS} -std=c++11")
include_directories("${TOP_SRCDIR}/src" "${KALDI_ROOT}/src" "${KALDI_ROOT}/tools/openfst/include" ${Python3_INCLUDE_DIRS})

find_package(SWIG REQUIRED)
include(${SWIG_USE_FILE})

swig_add_library(vosk TYPE SHARED LANGUAGE Python OUTPUT_DIR "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}" OUTFILE_DIR "."
SOURCES "${TOP_SRCDIR}/src/kaldi_recognizer.cc"
"${TOP_SRCDIR}/src/spk_model.cc"
"${TOP_SRCDIR}/src/model.cc"
"${TOP_SRCDIR}/src/vosk_api.cc"
"${TOP_SRCDIR}/src/vosk.i")

swig_link_libraries(vosk
${KALDI_ROOT}/src/online2/kaldi-online2.a
${KALDI_ROOT}/src/decoder/kaldi-decoder.a
${KALDI_ROOT}/src/ivector/kaldi-ivector.a
${KALDI_ROOT}/src/gmm/kaldi-gmm.a
${KALDI_ROOT}/src/nnet3/kaldi-nnet3.a
${KALDI_ROOT}/src/tree/kaldi-tree.a
${KALDI_ROOT}/src/feat/kaldi-feat.a
${KALDI_ROOT}/src/lat/kaldi-lat.a
${KALDI_ROOT}/src/lm/kaldi-lm.a
${KALDI_ROOT}/src/hmm/kaldi-hmm.a
${KALDI_ROOT}/src/transform/kaldi-transform.a
${KALDI_ROOT}/src/cudamatrix/kaldi-cudamatrix.a
${KALDI_ROOT}/src/matrix/kaldi-matrix.a
${KALDI_ROOT}/src/fstext/kaldi-fstext.a
${KALDI_ROOT}/src/util/kaldi-util.a
${KALDI_ROOT}/src/base/kaldi-base.a
${KALDI_ROOT}/tools/openfst/lib/libfst.a
${KALDI_ROOT}/tools/openfst/lib/libfstngram.a
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework -lstdc++)
set_target_properties(_vosk PROPERTIES LINK_FLAGS_RELEASE -s)
````

However, I still get this error:
**ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture x86_64:**

I have tried also to maintain the path to openblas.a but the error still the same. 

I have tried to clean my kaldi project and rebuild it again but it still giving me this error.
I have also replaced just the -lgfortran by the -framework Accelerate flag but it still gives me this error:
**ld: framework not found -lAccelerate**.

I don't really know what is happening, but it seems like some library is not being built properly. However, I get no errors when building kaldi and when installing the BLAS.

Has someone faced that kind of issues? Can you help me with this? 
Thanks in advance,
Regards

**Comment by nshmyrev** [comment]
@jose-alvessh it should be `-framework Accelerate`, not `-lAccelerate` and not `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework`

set_target_properties(_vosk PROPERTIES LINK_FLAGS_RELEASE "-framework Accelerate")

**Comment by jose-alvessh** [comment]
Hi @nshmyrev, sorry for bothering you. I did what you told me, but now I'm getting these errors:
**ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../lib.macosx-10.9-x86_64-3.7/vosk/_vosk.dylib] Error 1
make[2]: *** [CMakeFiles/_vosk.dir/all] Error 2
make[1]: *** [CMakeFiles/_vosk.dir/rule] Error 2
make: *** [_vosk] Error 2**
Seems like it is pointing to MacOSX 10.9 while I have the 10.15. Am I correct?

**Comment by nshmyrev** [comment]
> I did what you told me, but now I'm getting these errors:

The real errors are above the log you pasted I think. You need to provide the full log.

> Seems like it is pointing to MacOSX 10.9 while I have the 10.15. Am I correct?

It doesn't matter I think

**Comment by jose-alvessh** [comment]
Thanks for the help. Here it is the full log from above these. The build now goes until 100% and then fails with this error:

```
Undefined symbols for architecture x86_64:
  "_PyArg_UnpackTuple", referenced from:
      _SwigPyObject_own in voskPYTHON_wrap.c.o
  "_PyBool_FromLong", referenced from:
      _SwigPyObject_richcompare in voskPYTHON_wrap.c.o
      _SwigPyObject_own in voskPYTHON_wrap.c.o
  "_PyBuffer_Release", referenced from:
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
  "_PyBytes_AsStringAndSize", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      _SWIG_AsCharPtrAndSize in voskPYTHON_wrap.c.o
  "_PyCFunction_NewEx", referenced from:
      _SWIG_PyInstanceMethod_New in voskPYTHON_wrap.c.o
  "_PyCFunction_Type", referenced from:
      _SWIG_PyInstanceMethod_New in voskPYTHON_wrap.c.o
  "_PyCapsule_GetPointer", referenced from:
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
      _SWIG_Python_DestroyModule in voskPYTHON_wrap.c.o
  "_PyCapsule_Import", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
  "_PyCapsule_New", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
  "_PyDict_GetItem", referenced from:
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
  "_PyDict_New", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
  "_PyDict_SetItem", referenced from:
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
      _SWIG_Python_InitShadowInstance in voskPYTHON_wrap.c.o
  "_PyErr_Clear", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      __wrap_SetLogLevel in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
      _SWIG_Python_ConvertPtrAndOwn in voskPYTHON_wrap.c.o
      _SWIG_Python_GetSwigThis in voskPYTHON_wrap.c.o
      ...
  "_PyErr_Fetch", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyErr_Format", referenced from:
      _SWIG_Python_UnpackTuple in voskPYTHON_wrap.c.o
  "_PyErr_GivenExceptionMatches", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
  "_PyErr_Occurred", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_SetLogLevel in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
      _SWIG_Python_ConvertPtrAndOwn in voskPYTHON_wrap.c.o
      _SWIG_Python_GetSwigThis in voskPYTHON_wrap.c.o
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
      ...
  "_PyErr_Restore", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyErr_SetString", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyErr_WriteUnraisable", referenced from:
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyEval_InitThreads", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
  "_PyEval_RestoreThread", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyEval_SaveThread", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyExc_AttributeError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_IOError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_IndexError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_MemoryError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_OverflowError", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_SetLogLevel in voskPYTHON_wrap.c.o
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_RuntimeError", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyExc_SyntaxError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_SystemError", referenced from:
      _SWIG_Python_UnpackTuple in voskPYTHON_wrap.c.o
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_TypeError", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_SetLogLevel in voskPYTHON_wrap.c.o
      _SWIG_Python_UnpackTuple in voskPYTHON_wrap.c.o
      _SWIG_Python_InitShadowInstance in voskPYTHON_wrap.c.o
      _SwigPyObject_append in voskPYTHON_wrap.c.o
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_ValueError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyExc_ZeroDivisionError", referenced from:
      l_switch.table._wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyFloat_AsDouble", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
  "_PyFloat_Type", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
  "_PyGILState_Ensure", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyGILState_Release", referenced from:
      __wrap_new_Model in voskPYTHON_wrap.c.o
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      __wrap_new_SpkModel in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
      ...
  "_PyImport_AddModule", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
  "_PyInstanceMethod_New", referenced from:
      _SWIG_PyInstanceMethod_New in voskPYTHON_wrap.c.o
  "_PyLong_AsDouble", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
  "_PyLong_AsLong", referenced from:
      __wrap_SetLogLevel in voskPYTHON_wrap.c.o
  "_PyLong_FromLong", referenced from:
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
  "_PyLong_FromVoidPtr", referenced from:
      _SwigPyObject_long in voskPYTHON_wrap.c.o
  "_PyModule_AddObject", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
  "_PyModule_Create2", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
  "_PyModule_GetDict", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
  "_PyObject_Call", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
  "_PyObject_CallFunctionObjArgs", referenced from:
      _SWIG_Python_ConvertPtrAndOwn in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyObject_Free", referenced from:
      _SwigPyPacked_dealloc in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyObject_GenericGetAttr", referenced from:
      l___const.SwigPyPacked_TypeOnce.tmp in voskPYTHON_wrap.c.o
      l___const.SwigPyObject_TypeOnce.tmp in voskPYTHON_wrap.c.o
  "_PyObject_GetAttr", referenced from:
      _SWIG_Python_GetSwigThis in voskPYTHON_wrap.c.o
  "_PyObject_GetAttrString", referenced from:
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
      _SWIG_Python_InitShadowInstance in voskPYTHON_wrap.c.o
  "_PyObject_GetBuffer", referenced from:
      __wrap_KaldiRecognizer_AcceptWaveform in voskPYTHON_wrap.c.o
  "_PyObject_Init", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyObject_IsInstance", referenced from:
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
  "_PyObject_IsTrue", referenced from:
      _SwigPyObject_own in voskPYTHON_wrap.c.o
  "_PyObject_Malloc", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
  "_PyObject_SetAttr", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
  "_PyTuple_New", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
  "_PyTuple_SetItem", referenced from:
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
  "_PyType_IsSubtype", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
  "_PyType_Ready", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SWIG_Python_GetSwigThis in voskPYTHON_wrap.c.o
      _SWIG_Python_InitShadowInstance in voskPYTHON_wrap.c.o
      _SwigPyObject_append in voskPYTHON_wrap.c.o
      _SwigPyPacked_dealloc in voskPYTHON_wrap.c.o
      _SwigPyObject_dealloc in voskPYTHON_wrap.c.o
      ...
  "_PyType_Type", referenced from:
      _SwigPyClientData_New in voskPYTHON_wrap.c.o
  "_PyUnicode_AsUTF8String", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      _SWIG_AsCharPtrAndSize in voskPYTHON_wrap.c.o
  "_PyUnicode_Concat", referenced from:
      _SwigPyObject_repr in voskPYTHON_wrap.c.o
  "_PyUnicode_DecodeUTF8", referenced from:
      __wrap_KaldiRecognizer_Result in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_PartialResult in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_FinalResult in voskPYTHON_wrap.c.o
  "_PyUnicode_FromFormat", referenced from:
      __wrap_new_KaldiRecognizer in voskPYTHON_wrap.c.o
      _SwigPyPacked_repr in voskPYTHON_wrap.c.o
      _SwigPyPacked_str in voskPYTHON_wrap.c.o
      _SwigPyObject_repr in voskPYTHON_wrap.c.o
  "_PyUnicode_FromString", referenced from:
      _PyInit__vosk in voskPYTHON_wrap.c.o
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
      _SWIG_pchar_descriptor in voskPYTHON_wrap.c.o
      _SWIG_Python_GetSwigThis in voskPYTHON_wrap.c.o
      _SWIG_Python_InitShadowInstance in voskPYTHON_wrap.c.o
      _SwigPyPacked_str in voskPYTHON_wrap.c.o
      _SWIG_Python_DestroyModule in voskPYTHON_wrap.c.o
      ...
  "_Py_DecRef", referenced from:
      _SwigPyObject_repr in voskPYTHON_wrap.c.o
  "__PyObject_New", referenced from:
      _SWIG_Python_NewPointerObj in voskPYTHON_wrap.c.o
  "__Py_NoneStruct", referenced from:
      __wrap_delete_Model in voskPYTHON_wrap.c.o
      _Model_swigregister in voskPYTHON_wrap.c.o
      __wrap_delete_SpkModel in voskPYTHON_wrap.c.o
      _SpkModel_swigregister in voskPYTHON_wrap.c.o
      __wrap_delete_KaldiRecognizer in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_Result in voskPYTHON_wrap.c.o
      __wrap_KaldiRecognizer_PartialResult in voskPYTHON_wrap.c.o
      ...
  "__Py_NotImplementedStruct", referenced from:
      _SwigPyObject_richcompare in voskPYTHON_wrap.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../lib.macosx-10.9-x86_64-3.7/vosk/_vosk.dylib] Error 1
make[2]: *** [CMakeFiles/_vosk.dir/all] Error 2
make[1]: *** [CMakeFiles/_vosk.dir/rule] Error 2
make: *** [_vosk] Error 2
Traceback (most recent call last):
```

**Comment by nshmyrev** [comment]
Try to add ${Python3_LIBRARIES} to swig_link_libraries.

**Comment by jose-alvessh** [comment]
@nshmyrev Thank you, it worked and I was able to install it, however when I try to run the example script `python3 ./test_simple.py test.wav`, I'm getting this error: 
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/Users/myusername/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/Users/myusername/Library/Python/3.7/lib/python/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: cannot import name '_vosk' from 'vosk' (/Users/myusername/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py)

I have tried to clean these folders /Users/myusername/Library/Python/3.7/lib/python/site-packages/vosk as you mentioned in this [issue](https://github.com/alphacep/vosk-api/issues/85). The file _vosk.dylib is placed inside this folder /Users/myusername/Library/Python/3.7/lib/python/site-packages/vosk so I can't really understand why this issue is happening. Can you help me on this?

**Comment by nshmyrev** [comment]
Run `otool -L _vosk.dylib` to see what dependencies are missing probably.

**Comment by jose-alvessh** [comment]
I'm getting this:
_vosk.dylib:
	@rpath/_vosk.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	@rpath/Python3.framework/Versions/3.7/Python3 (compatibility version 3.7.0, current version 3.7.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)

**Comment by nshmyrev** [comment]
run `python3 ./test_simple.py test.wav` and provide the output

**Comment by jose-alvessh** [comment]
I'm getting the error:
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/Users/josealves/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/Users/josealves/Library/Python/3.7/lib/python/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: cannot import name '_vosk' from 'vosk' (/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py)

**Comment by nshmyrev** [comment]
Run `python3 -v ./test_simple.py test.wav` and provide the output.

**Comment by jose-alvessh** [comment]
It gives a huge output by I think that this is the part that interests for this problem: 
Type "help", "copyright", "credits" or "license" for more information.
/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__pycache__/__init__.cpython-37.pyc matches /Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py
code object from '/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__pycache__/__init__.cpython-37.pyc'
/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__pycache__/vosk.cpython-37.pyc matches /Users/username/Library/Python/3.7/lib/python/site-packages/vosk/vosk.py
code object from '/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__pycache__/vosk.cpython-37.pyc'
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/josealves/Library/Python/3.7/lib/python/site-packages/vosk/vosk.py", line 13, in <module>
    from . import _vosk
ImportError: cannot import name '_vosk' from 'vosk' (/Users/username/Library/Python/3.7/lib/python/site-packages/vosk/__init__.py)

**Comment by nshmyrev** [comment]
_vosk.dylib should be _vosk.so, then it will load. You can wait a bit, I'll commit required makefile changes and share the wheels.

**Comment by nshmyrev** [comment]
I have published all changes and wheel too:

https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp38-cp38-macosx_10_12_x86_64.whl

check if it works for you.

**Comment by jose-alvessh** [comment]
Hi @nshmyrev. Thanks. I was able to install vosk with this wheel file.
Still, I'm getting this error when trying to run `python3 ./test_simple.py test.wav`:
Traceback (most recent call last):
  File "./test_simple.py", line 3, in <module>
    from vosk import Model, KaldiRecognizer, SetLogLevel
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vosk/__init__.py", line 1, in <module>
    from .vosk import KaldiRecognizer, Model, SpkModel, SetLogLevel
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vosk/vosk.py", line 28, in <module>
    _vosk = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vosk/vosk.py", line 24, in swig_import_helper
    _mod = imp.load_module('_vosk', fp, pathname, description)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vosk/_vosk.so, 2): Library not loaded: /opt/local/Library/Frameworks/Python.framework/Versions/3.8/Python
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/vosk/_vosk.so
  Reason: image not found

Then I decided to pull the changes that you have made to the repository and compile it from scratch. **I was finally able to run the python scripts.** I don't have sure that the pip3 install vosk is working for mac, but compiling it following the Readme is now working. 
Thank you so much for your help.

**Comment by nshmyrev** [comment]
Ok, I pushed a fix for this and updated the wheel here:

https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp38-cp38-macosx_10_12_x86_64.whl

on next release it will go to pypi. Thanks for the testing.

**Comment by sampathkethineedi** [comment]
Hi @nshmyrev, Still getting this error for MacOS 10.15.4

`pip3 install https://github.com/alphacep/vosk-api/releases/download/0.3.7/vosk-0.3.7-cp38-cp38-macosx_10_12_x86_64.whl`

`ERROR: vosk-0.3.7-cp38-cp38-macosx_10_12_x86_64.whl is not a supported wheel on this platform.
`

**Comment by nshmyrev** [comment]
@sampathkethineedi provide the output of 

```
python3 --version
pip3 --version
pip3 -v install vosk
```

Most likely you have version mismatch.

**Comment by sampathkethineedi** [comment]
@nshmyrev 

`Python 3.7.7`
`pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

pip3 -v install vosk
`pip._internal.exceptions.DistributionNotFound: No matching distribution found for vosk`

**Comment by nshmyrev** [comment]
> Python 3.7.7

We only support python 3.8 on osx, please upgrade.
